title: Russ Shomberg
description: >- # this means to ignore newlines until "baseurl:"

  Ocean Systems Engineer

baseurl: /
repository: rshom/rshom.github.io

author: "Russ Shomberg"
theme: minima
domain: rshom.github.io
url: https://rshom.github.io

#twitter_username: russellshomberg
github_username:  rshom
linkedin_username: rshomberg
# TODO: include email

# Minima: show excerpts in the frontpage
#show_excerpts: true
page_excerpts: true
excerpt_separator: "\n\n"

minima:
  date_format: "%Y-%m-%d"

header_pages:
  - _pages/about.md
  - _pages/work.md
  #- _pages/fun.md
  #- _pages/blog.md
  #- _pages/archive.md

include:
    - _pages
    - _projects

collections:
  projects:
    output: true
    sort_by: date

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md

# Build settings
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
